coverage:
  status:
    project:
      default:
        threshold: 1%
    patch: off
ignore:
  - "internal/controlpb/control*"  # generated code
  - "client_experimental.go"  # experimental code
  - "internal/websocket/*"  # embedded Gorilla WebSocket fork
