language: go

env:
  - GO111MODULE=on

go:
  - "1.13.x"
  - "1.14.x"
  - tip

services:
  - redis-server

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -race -tags integration -coverprofile=cover.out $(go list ./... | grep -v /_examples/)

deploy:
  - provider: script
    script: goveralls -service=travis-ci -coverprofile=cover.out
    on:
      go: '1.14.x'
