language: go

env:
  - GO111MODULE=on

go:
  - "1.13.x"
  - "1.14.x"
  - tip

services:
  - redis

before_install:
  - go get github.com/mattn/goveralls
  - docker pull grokzen/redis-cluster:latest
  - docker run -d -e "IP=0.0.0.0" -p 7000-7006:7000-7006 grokzen/redis-cluster:latest
  - docker run -d -p 26379:26379 joshula/redis-sentinel:latest --sentinel announce-ip 1.2.3.4 --sentinel announce-port 26379

script:
  - go test -v -race -tags integration -coverprofile=cover.out $(go list ./... | grep -v /_examples/)

after_success:
  - 'if [[ "$TRAVIS_GO_VERSION" =~ ^1\.14 ]]; then goveralls -ignore "internal/controlpb/control*" -service=travis-ci -coverprofile=cover.out; fi'
