package centrifuge

import (
	"github.com/centrifugal/protocol"
)

// Define some aliases to internal protocol types generated by gogo/protobuf.
// This allows us to simply expose only subset of useful types to centrifuge
// package keeping types that is not supposed to be in public API hidden from
// library users.
type (
	// Error represents client reply error.
	Error = protocol.Error
	// Raw represents raw bytes.
	Raw = protocol.Raw
	// Publication allows to deliver custom payload to all channel subscribers.
	Publication = protocol.Publication
	// ClientInfo is short information about client connection.
	ClientInfo = protocol.ClientInfo
	// ProtocolType represents client connection transport encoding format.
	ProtocolType = protocol.Type
	// EncodingType represents client payload encoding format.
	EncodingType = protocol.EncodingType
)

// Protocol types.
const (
	ProtocolTypeJSON     = protocol.TypeJSON
	ProtocolTypeProtobuf = protocol.TypeProtobuf
)

// Encoding types.
const (
	EncodingTypeJSON   = protocol.EncodingTypeJSON
	EncodingTypeBinary = protocol.EncodingTypeBinary
)
