version: "3.9"
services:
  tnt1:
    container_name: tnt1
    image: tarantool/tarantool:2.7.0
    volumes:
      - .:/opt/tarantool/
    command: tarantool ha.lua 1
    ports:
      - 3301:3301
  tnt2:
    container_name: tnt2
    image: tarantool/tarantool:2.7.0
    volumes:
      - .:/opt/tarantool/
    command: tarantool ha.lua 2
    ports:
      - 3302:3302
  tnt3:
    container_name: tnt3
    image: tarantool/tarantool:2.7.0
    volumes:
      - .:/opt/tarantool/
    command: tarantool ha.lua 3
    ports:
      - 3303:3303
