# Generates the TLC configs of Subscriptions.tla into configs/
# (python3 tla/client/gen_configs.py).
import os

CONFIGS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'configs')
os.makedirs(CONFIGS_DIR, exist_ok=True)

BASE = dict(
    Chans='{"c1"}', ClientChans='{"c1"}', ServerChans='{}',
    MaxCmds=3, MaxPubs=2, MaxOffsetless=0, MaxServerUnsubs=1, UnsubWhileSubscribing='FALSE', MaxServerSubs=0, MaxIns=1,
    ConnectSub='FALSE', Positioned='TRUE', Lossy='FALSE', JoinLeave='FALSE',
    CloseAllowed='TRUE', Timeouts='FALSE', DoubleInvoke='FALSE',
    Answers='{"allow", "deny", "refuse", "closedErr"}',
    MaxDisconnects=0, SlowWrite='FALSE', StaleTimer='FALSE', RefreshMode='"none"',
    MaxRefreshes=0, MaxExtends=0, RefreshAnswers='{}', MaxTicks=0, SubExpiry='"none"',
    MaxSubRefreshes=0, MaxEpochs=1, LaggingReplica='FALSE', HistorySize=0, BufferLimit=0,
    Bugs='{}')

SAFETY = ['TypeOK', 'AtMostOneUnsubscribeHandler', 'UnsubscribeBeforeNextSubscribe',
          'NothingAfterDisconnectHandler', 'NoUnsubscribeHandlerDuringConnectHandler',
          'LeaveAfterJoin', 'JoinAfterPreviousLeave', 'NoPublicationOutsideSubscription', 'ContiguousOffsets',
          'NoUnsubscribePushAfterLaterResult', 'ConsistentAtQuiescence', 'CleanAfterClose',
          'DisconnectHandlerOnce', 'DisconnectFrameOfWinner', 'NothingAfterDisconnectFrame',
          'NoExpireTimerOnClosedClient', 'NoRefreshOrExpiryOfOtherSubscription',
          'NoPublicationOfAnotherEpochDropped']
# With Timeouts the documented 5s/30s exceptions apply: a SubscribeHandler may
# come before the UnsubscribeHandler of an earlier attempt, a resubscribe may stop
# waiting for the previous subscription's leave and unsubscribe push, calls may
# come after DisconnectHandler. An unsubscribe whose wait for a subscribe in
# progress timed out replies and disconnects the client (go c.close): until the
# disconnect, publications may follow its reply, and the abandoned attempt may
# still write its (stale, ignored by the SDK) reply, so the wire properties are
# not checked. When the 5s wait for the previous unsubscribe's push times out, the
# push can come after the new subscription's reply and the SDK ends the new
# subscription while the server keeps it, so ConsistentAtQuiescence is replaced
# by its handler-call/tracking part, ReleasedAtQuiescence.
TIMEOUT_SAFETY = [i for i in SAFETY if i not in (
    'UnsubscribeBeforeNextSubscribe', 'NothingAfterDisconnectHandler',
    'NoPublicationOutsideSubscription', 'NoUnsubscribePushAfterLaterResult',
    'ContiguousOffsets', 'JoinAfterPreviousLeave', 'ConsistentAtQuiescence')] + ['ReleasedAtQuiescence']
SERVER = dict(ClientChans='{}', ServerChans='{"c1"}', MaxCmds=0)


def w(name, inv=SAFETY, spec='Spec', props=(), view=True, **kw):
    d = dict(BASE)
    d.update(kw)
    with open(os.path.join(CONFIGS_DIR, name), 'w') as f:
        f.write('\\* Generated by gen_configs.py\nCONSTANTS\n')
        f.write(''.join('  %s = %s\n' % (k, v) for k, v in d.items()))
        f.write('SPECIFICATION %s\n' % spec)
        if view:
            f.write('VIEW View\n')
        f.write('INVARIANTS\n' + ''.join('  %s\n' % i for i in inv))
        if props:
            f.write('PROPERTIES\n' + ''.join('  %s\n' % p for p in props))


def bugs(*names):
    return '{' + ', '.join('"%s"' % n for n in names) + '}'



# Main configurations: the current code. Each must pass.
w('MC_small.cfg', MaxPubs=1, MaxOffsetless=1)
w('MC_double_invoke.cfg', MaxPubs=0, DoubleInvoke='TRUE')
w('MC_large.cfg', MaxOffsetless=1, JoinLeave='TRUE', Lossy='TRUE')
w('MC_not_positioned.cfg', Positioned='FALSE', MaxOffsetless=1)
w('MC_server.cfg', MaxServerSubs=2, MaxServerUnsubs=2, JoinLeave='TRUE', **SERVER)
w('MC_connect.cfg', ConnectSub='TRUE', MaxServerSubs=1, MaxServerUnsubs=2, JoinLeave='TRUE',
  **SERVER)
w('MC_two_channels.cfg', Chans='{"c1", "c2"}', ClientChans='{"c1", "c2"}', MaxCmds=3,
  MaxPubs=0, MaxServerUnsubs=1, MaxIns=0)
w('MC_timeouts.cfg', inv=TIMEOUT_SAFETY, Timeouts='TRUE', MaxPubs=1)
w('MC_liveness.cfg', inv=[], spec='SpecAnswering', view=False, MaxCmds=2, MaxPubs=1,
  MaxIns=0, Answers='{"allow", "refuse"}', CloseAllowed='FALSE',
  props=['AllowedAttemptReleased', 'SubscribeCommandReplied', 'PublicationDelivered'])
w('MC_liveness_close.cfg', inv=[], spec='SpecAnswering', view=False, MaxCmds=2, MaxPubs=0,
  MaxIns=0, Answers='{"allow", "deny", "refuse"}',
  props=['AllowedAttemptReleased', 'SubscribeCommandReplied'])

# Connection lifecycle: concurrent closes (transport, Client.Disconnect, slow
# queue, expiry, stale timer), disconnects during connect and ConnectHandler,
# expiry and refresh.
CONN = dict(ClientChans='{}', ServerChans='{"c1"}', MaxCmds=0, ConnectSub='TRUE', MaxPubs=0,
            MaxServerUnsubs=0, MaxIns=0, MaxDisconnects=1, SlowWrite='TRUE', StaleTimer='TRUE',
            RefreshAnswers='{"extend", "expired", "error"}', MaxRefreshes=1, MaxExtends=1)
w('MC_connection.cfg', RefreshMode='"server"', **dict(CONN, MaxExtends=0))
w('MC_connection_client_refresh.cfg', RefreshMode='"client"', **CONN)
w('MC_connection_large.cfg', RefreshMode='"server"', **dict(CONN, MaxPubs=1))
w('MC_liveness_expiry.cfg', inv=[], spec='SpecAnswering', view=False,
  props=['ExpiredConnectionClosed', 'AllowedAttemptReleased'], RefreshMode='"server"',
  **dict(CONN, MaxDisconnects=0, SlowWrite='FALSE', CloseAllowed='FALSE', MaxExtends=2))

# Presence ticks racing unsubscribes and resubscribes; subscription expiry and
# refresh (subGen identity).
TICK = dict(JoinLeave='TRUE', MaxTicks=2, MaxPubs=0)
w('MC_presence_tick.cfg', **TICK)
SUBEXP = dict(MaxPubs=0, MaxIns=0, Answers='{"allow", "deny"}')
w('MC_sub_expiry_server.cfg', SubExpiry='"server"', MaxTicks=2, **SUBEXP)
w('MC_sub_expiry_client.cfg', SubExpiry='"client"', MaxTicks=1, MaxSubRefreshes=1, **SUBEXP)

# Recovery details: epoch change during subscribe, unrecoverable position,
# buffer overflow (ClientQueueMaxSize), empty-epoch read from a lagging replica.
REC = dict(MaxEpochs=2, MaxPubs=2, MaxServerUnsubs=0, MaxIns=1, CloseAllowed='FALSE')
w('MC_recovery_epoch.cfg', **REC)
w('MC_recovery_lagging_replica.cfg', LaggingReplica='TRUE', **REC)
w('MC_recovery_history_overflow.cfg', HistorySize=1, BufferLimit=1, **dict(REC, MaxEpochs=1))

w('bug_empty_epoch_kept_after_merge.cfg', Bugs=bugs('EmptyEpochKeptAfterMerge'),
  LaggingReplica='TRUE', **REC)

# Bug variants: old behaviours, each must fail.
w('bug_push_after_handler.cfg', Bugs=bugs('PushAfterHandler'))
w('bug_push_after_handler_wire.cfg', Bugs=bugs('PushAfterHandler'),
  inv=['NoUnsubscribePushAfterLaterResult', 'ConsistentAtQuiescence'])
# Client.Unsubscribe while Client.Subscribe is in progress. Releasing the
# unsubscribe before StopBuffering only shows while queued publications are
# also written outside c.mu (the old code had both).
w('bug_server_sub_early_release.cfg', Bugs=bugs('ServerSubEarlyRelease', 'PendingWriteUnlocked'),
  MaxServerSubs=1, UnsubWhileSubscribing='TRUE', **SERVER)
# The disconnect push enqueued before the writer is closed: frames after it.
w('bug_disconnect_push_not_last.cfg', Bugs=bugs('DisconnectPushNotLast'), RefreshMode='"none"',
  **dict(CONN, MaxRefreshes=0, MaxExtends=0, RefreshAnswers='{}'))
SMALLBUG = dict(MaxServerUnsubs=0, MaxIns=0, CloseAllowed='FALSE', Answers='{"allow"}')
w('bug_cras_single_wait.cfg', Bugs=bugs('CrasSingleWait'), **TICK)
w('bug_tick_remove_no_pending_leave.cfg', Bugs=bugs('TickRemoveNoPendingLeave'), **dict(TICK, **SMALLBUG))
w('bug_tick_remove_ignores_subscription.cfg', Bugs=bugs('TickRemoveIgnoresSubscription'),
  **dict(TICK, **SMALLBUG))
w('bug_sub_refresh_no_gen_check.cfg', Bugs=bugs('SubRefreshNoGenCheck'), SubExpiry='"server"',
  MaxTicks=2, MaxPubs=0, **SMALLBUG)
w('bug_async_unsubscribe_any_gen.cfg', Bugs=bugs('AsyncUnsubscribeAnyGen'), SubExpiry='"client"',
  MaxTicks=1, MaxPubs=0, **SMALLBUG)
w('bug_no_attempt_end_call.cfg', Bugs=bugs('NoAttemptEndCall'))
# Liveness has teeth: without attempt-end calls an allowed attempt is never released.
w('bug_no_attempt_end_call_liveness.cfg', inv=[], spec='SpecAnswering', view=False, MaxCmds=2,
  MaxPubs=0, MaxIns=0, Answers='{"allow", "refuse"}', CloseAllowed='FALSE',
  Bugs=bugs('NoAttemptEndCall'), props=['AllowedAttemptReleased'])
w('bug_no_join_gate.cfg', Bugs=bugs('NoJoinGate'), JoinLeave='TRUE', MaxPubs=0)
w('bug_server_unsub_not_ordered.cfg', Bugs=bugs('ServerUnsubNotOrdered'))
w('bug_no_connect_defer.cfg', Bugs=bugs('NoConnectDefer'), ConnectSub='TRUE', MaxServerSubs=1,
  **SERVER)
w('bug_no_attempt_end_wait.cfg', Bugs=bugs('NoAttemptEndWait'))
w('bug_pending_write_unlocked.cfg', Bugs=bugs('PendingWriteUnlocked'), MaxServerUnsubs=0,
  CloseAllowed='FALSE')
# The same window, its effect on a resubscribe: a duplicate after the new result.
w('bug_pending_write_unlocked_duplicate.cfg', Bugs=bugs('PendingWriteUnlocked'),
  MaxServerUnsubs=0, CloseAllowed='FALSE', inv=['ContiguousOffsets', 'ConsistentAtQuiescence'])
w('bug_pending_write_unlocked_server.cfg', Bugs=bugs('PendingWriteUnlocked'), MaxServerSubs=1,
  inv=['NoPublicationOutsideSubscription'], **SERVER)
w('bug_merge_no_gap_check.cfg', Bugs=bugs('MergeNoGapCheck'), Lossy='TRUE', MaxPubs=3,
  MaxServerUnsubs=0, CloseAllowed='FALSE')
w('bug_no_wait_other_after_subscribe.cfg', Bugs=bugs('NoWaitOtherAfterSubscribe'),
  MaxOffsetless=1, MaxPubs=0, CloseAllowed='FALSE')
w('bug_offsetless_before_result.cfg', Bugs=bugs('OffsetlessBeforeResult'), Positioned='FALSE',
  MaxOffsetless=1, MaxPubs=0, MaxServerUnsubs=0, CloseAllowed='FALSE', MaxCmds=1)
