// Code generated by cfprotobuf. DO NOT EDIT.

package controlpb

import (
	"encoding/binary"
	"math"

	cfprotobuf "github.com/centrifugal/protocol/cfprotobuf"
)

// SizeCF returns the size of the Protobuf encoding of m.
func (m *Command) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.Uid != "" {
		n += 1 + len(m.Uid) + cfprotobuf.SizeOfLen(len(m.Uid))
	}
	if m.Node != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Node.SizeCF())
	}
	if m.Unsubscribe != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Unsubscribe.SizeCF())
	}
	if m.Disconnect != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Disconnect.SizeCF())
	}
	if m.Shutdown != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Shutdown.SizeCF())
	}
	if m.SurveyRequest != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.SurveyRequest.SizeCF())
	}
	if m.SurveyResponse != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.SurveyResponse.SizeCF())
	}
	if m.Subscribe != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Subscribe.SizeCF())
	}
	if m.Notification != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Notification.SizeCF())
	}
	if m.Refresh != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Refresh.SizeCF())
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *Command) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *Command) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *Command) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.Refresh != nil {
		{
			size, err := m.Refresh.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x62
	}
	if m.Notification != nil {
		{
			size, err := m.Notification.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x5a
	}
	if m.Subscribe != nil {
		{
			size, err := m.Subscribe.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x52
	}
	if m.SurveyResponse != nil {
		{
			size, err := m.SurveyResponse.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x4a
	}
	if m.SurveyRequest != nil {
		{
			size, err := m.SurveyRequest.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x42
	}
	if m.Shutdown != nil {
		{
			size, err := m.Shutdown.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x3a
	}
	if m.Disconnect != nil {
		{
			size, err := m.Disconnect.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x32
	}
	if m.Unsubscribe != nil {
		{
			size, err := m.Unsubscribe.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x2a
	}
	if m.Node != nil {
		{
			size, err := m.Node.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x22
	}
	if m.Uid != "" {
		i -= len(m.Uid)
		copy(b[i:], m.Uid)
		i = cfprotobuf.PutLen(b, i, len(m.Uid))
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Command) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *Command) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // Uid
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Uid = string(s)
				i = to
				continue
			}
		case 4: // Node
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Node == nil {
					m.Node = new(Node)
				}
				if err := m.Node.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 5: // Unsubscribe
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Unsubscribe == nil {
					m.Unsubscribe = new(Unsubscribe)
				}
				if err := m.Unsubscribe.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 6: // Disconnect
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Disconnect == nil {
					m.Disconnect = new(Disconnect)
				}
				if err := m.Disconnect.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 7: // Shutdown
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Shutdown == nil {
					m.Shutdown = new(Shutdown)
				}
				if err := m.Shutdown.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 8: // SurveyRequest
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.SurveyRequest == nil {
					m.SurveyRequest = new(SurveyRequest)
				}
				if err := m.SurveyRequest.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 9: // SurveyResponse
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.SurveyResponse == nil {
					m.SurveyResponse = new(SurveyResponse)
				}
				if err := m.SurveyResponse.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 10: // Subscribe
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Subscribe == nil {
					m.Subscribe = new(Subscribe)
				}
				if err := m.Subscribe.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 11: // Notification
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Notification == nil {
					m.Notification = new(Notification)
				}
				if err := m.Notification.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 12: // Refresh
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Refresh == nil {
					m.Refresh = new(Refresh)
				}
				if err := m.Refresh.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *Shutdown) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *Shutdown) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *Shutdown) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *Shutdown) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Shutdown) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *Shutdown) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *Node) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.Uid != "" {
		n += 1 + len(m.Uid) + cfprotobuf.SizeOfLen(len(m.Uid))
	}
	if m.Name != "" {
		n += 1 + len(m.Name) + cfprotobuf.SizeOfLen(len(m.Name))
	}
	if m.Version != "" {
		n += 1 + len(m.Version) + cfprotobuf.SizeOfLen(len(m.Version))
	}
	if m.NumClients != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.NumClients)
	}
	if m.NumUsers != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.NumUsers)
	}
	if m.NumChannels != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.NumChannels)
	}
	if m.Uptime != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Uptime)
	}
	if m.Metrics != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Metrics.SizeCF())
	}
	if len(m.Data) > 0 {
		n += 1 + len(m.Data) + cfprotobuf.SizeOfLen(len(m.Data))
	}
	if m.NumSubs != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.NumSubs)
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *Node) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *Node) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *Node) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.NumSubs != 0 {
		i = cfprotobuf.PutInt(b, i, m.NumSubs)
		i--
		b[i] = 0x50
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(b[i:], m.Data)
		i = cfprotobuf.PutLen(b, i, len(m.Data))
		i--
		b[i] = 0x4a
	}
	if m.Metrics != nil {
		{
			size, err := m.Metrics.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x42
	}
	if m.Uptime != 0 {
		i = cfprotobuf.PutInt(b, i, m.Uptime)
		i--
		b[i] = 0x38
	}
	if m.NumChannels != 0 {
		i = cfprotobuf.PutInt(b, i, m.NumChannels)
		i--
		b[i] = 0x30
	}
	if m.NumUsers != 0 {
		i = cfprotobuf.PutInt(b, i, m.NumUsers)
		i--
		b[i] = 0x28
	}
	if m.NumClients != 0 {
		i = cfprotobuf.PutInt(b, i, m.NumClients)
		i--
		b[i] = 0x20
	}
	if m.Version != "" {
		i -= len(m.Version)
		copy(b[i:], m.Version)
		i = cfprotobuf.PutLen(b, i, len(m.Version))
		i--
		b[i] = 0x1a
	}
	if m.Name != "" {
		i -= len(m.Name)
		copy(b[i:], m.Name)
		i = cfprotobuf.PutLen(b, i, len(m.Name))
		i--
		b[i] = 0x12
	}
	if m.Uid != "" {
		i -= len(m.Uid)
		copy(b[i:], m.Uid)
		i = cfprotobuf.PutLen(b, i, len(m.Uid))
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Node) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *Node) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // Uid
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Uid = string(s)
				i = to
				continue
			}
		case 2: // Name
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Name = string(s)
				i = to
				continue
			}
		case 3: // Version
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Version = string(s)
				i = to
				continue
			}
		case 4: // NumClients
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.NumClients = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 5: // NumUsers
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.NumUsers = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 6: // NumChannels
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.NumChannels = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 7: // Uptime
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Uptime = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 8: // Metrics
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Metrics == nil {
					m.Metrics = new(Metrics)
				}
				if err := m.Metrics.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 9: // Data
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				m.Data = append(m.Data[:0], b[from:to]...)
				if m.Data == nil {
					m.Data = []byte{}
				}
				i = to
				continue
			}
		case 10: // NumSubs
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.NumSubs = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *Metrics) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.Interval != 0 {
		n += 1 + 8
	}
	if len(m.Items) > 0 {
		for k := range m.Items {
			entry := 1 + len(k) + cfprotobuf.SizeOfLen(len(k)) + 1 + 8
			n += 1 + entry + cfprotobuf.SizeOfLen(entry)
		}
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *Metrics) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *Metrics) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *Metrics) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if len(m.Items) > 0 {
		for k, v := range m.Items {
			end := i
			i -= 8
			binary.LittleEndian.PutUint64(b[i:], math.Float64bits(v))
			i--
			b[i] = 0x11
			i -= len(k)
			copy(b[i:], k)
			i = cfprotobuf.PutLen(b, i, len(k))
			i--
			b[i] = 0xa
			i = cfprotobuf.PutLen(b, i, end-i)
			i--
			b[i] = 0x12
		}
	}
	if m.Interval != 0 {
		i -= 8
		binary.LittleEndian.PutUint64(b[i:], math.Float64bits(m.Interval))
		i--
		b[i] = 0x9
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Metrics) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *Metrics) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // Interval
			if tag&7 == 1 {
				if len(b)-i < 8 {
					return cfprotobuf.ErrTruncated
				}
				m.Interval = math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
				i += 8
				continue
			}
		case 2: // Items
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Items == nil {
					m.Items = make(map[string]float64)
				}
				entry := b[from:to]
				var key string
				var val float64
				for j := 0; j < len(entry); {
					entryTag := uint64(entry[j])
					next = j + 1
					if entryTag >= 0x80 {
						if entryTag, next = cfprotobuf.Varint(entry, j); next < 0 {
							return cfprotobuf.Error(next)
						}
					}
					j = next
					switch entryTag {
					case 10:
						fromKey := j + 1
						var toKey int
						if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromKey {
							toKey = fromKey + int(entry[j])
						} else if fromKey, toKey = cfprotobuf.Length(entry, j); fromKey < 0 {
							return cfprotobuf.Error(fromKey)
						}
						sKey := entry[fromKey:toKey]
						if !cfprotobuf.ShortASCII(sKey) && !cfprotobuf.ValidString(sKey) {
							return cfprotobuf.ErrInvalidUTF8
						}
						key = string(sKey)
						j = toKey
					case 17:
						if len(entry)-j < 8 {
							return cfprotobuf.ErrTruncated
						}
						val = math.Float64frombits(binary.LittleEndian.Uint64(entry[j:]))
						j += 8
					default:
						next = cfprotobuf.Skip(entry, j, entryTag)
						if next < 0 {
							return cfprotobuf.Error(next)
						}
						j = next
					}
				}
				m.Items[key] = val
				i = to
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *Subscribe) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.User != "" {
		n += 1 + len(m.User) + cfprotobuf.SizeOfLen(len(m.User))
	}
	if m.Channel != "" {
		n += 1 + len(m.Channel) + cfprotobuf.SizeOfLen(len(m.Channel))
	}
	if m.EmitPresence {
		n += 1 + 1
	}
	if m.EmitJoinLeave {
		n += 1 + 1
	}
	if m.ExpireAt != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.ExpireAt)
	}
	if m.Position {
		n += 1 + 1
	}
	if m.Recover {
		n += 1 + 1
	}
	if len(m.ChannelInfo) > 0 {
		n += 1 + len(m.ChannelInfo) + cfprotobuf.SizeOfLen(len(m.ChannelInfo))
	}
	if m.Client != "" {
		n += 1 + len(m.Client) + cfprotobuf.SizeOfLen(len(m.Client))
	}
	if len(m.Data) > 0 {
		n += 1 + len(m.Data) + cfprotobuf.SizeOfLen(len(m.Data))
	}
	if m.RecoverSince != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.RecoverSince.SizeCF())
	}
	if m.Session != "" {
		n += 1 + len(m.Session) + cfprotobuf.SizeOfLen(len(m.Session))
	}
	if m.PushJoinLeave {
		n += 1 + 1
	}
	if m.Source != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Source)
	}
	if m.LabelFilter != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.LabelFilter.SizeCF())
	}
	if m.AllUsers {
		n += 2 + 1
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *Subscribe) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *Subscribe) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *Subscribe) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.AllUsers {
		i--
		b[i] = 1
		i--
		b[i] = 0x1
		i--
		b[i] = 0x80
	}
	if m.LabelFilter != nil {
		{
			size, err := m.LabelFilter.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x7a
	}
	if m.Source != 0 {
		i = cfprotobuf.PutInt(b, i, m.Source)
		i--
		b[i] = 0x70
	}
	if m.PushJoinLeave {
		i--
		b[i] = 1
		i--
		b[i] = 0x68
	}
	if m.Session != "" {
		i -= len(m.Session)
		copy(b[i:], m.Session)
		i = cfprotobuf.PutLen(b, i, len(m.Session))
		i--
		b[i] = 0x62
	}
	if m.RecoverSince != nil {
		{
			size, err := m.RecoverSince.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x5a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(b[i:], m.Data)
		i = cfprotobuf.PutLen(b, i, len(m.Data))
		i--
		b[i] = 0x52
	}
	if m.Client != "" {
		i -= len(m.Client)
		copy(b[i:], m.Client)
		i = cfprotobuf.PutLen(b, i, len(m.Client))
		i--
		b[i] = 0x4a
	}
	if len(m.ChannelInfo) > 0 {
		i -= len(m.ChannelInfo)
		copy(b[i:], m.ChannelInfo)
		i = cfprotobuf.PutLen(b, i, len(m.ChannelInfo))
		i--
		b[i] = 0x42
	}
	if m.Recover {
		i--
		b[i] = 1
		i--
		b[i] = 0x38
	}
	if m.Position {
		i--
		b[i] = 1
		i--
		b[i] = 0x30
	}
	if m.ExpireAt != 0 {
		i = cfprotobuf.PutInt(b, i, m.ExpireAt)
		i--
		b[i] = 0x28
	}
	if m.EmitJoinLeave {
		i--
		b[i] = 1
		i--
		b[i] = 0x20
	}
	if m.EmitPresence {
		i--
		b[i] = 1
		i--
		b[i] = 0x18
	}
	if m.Channel != "" {
		i -= len(m.Channel)
		copy(b[i:], m.Channel)
		i = cfprotobuf.PutLen(b, i, len(m.Channel))
		i--
		b[i] = 0x12
	}
	if m.User != "" {
		i -= len(m.User)
		copy(b[i:], m.User)
		i = cfprotobuf.PutLen(b, i, len(m.User))
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Subscribe) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *Subscribe) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // User
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.User = string(s)
				i = to
				continue
			}
		case 2: // Channel
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Channel = string(s)
				i = to
				continue
			}
		case 3: // EmitPresence
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.EmitPresence = v != 0
				i = next
				continue
			}
		case 4: // EmitJoinLeave
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.EmitJoinLeave = v != 0
				i = next
				continue
			}
		case 5: // ExpireAt
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.ExpireAt = cfprotobuf.Int[int64](v)
				i = next
				continue
			}
		case 6: // Position
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Position = v != 0
				i = next
				continue
			}
		case 7: // Recover
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Recover = v != 0
				i = next
				continue
			}
		case 8: // ChannelInfo
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				m.ChannelInfo = append(m.ChannelInfo[:0], b[from:to]...)
				if m.ChannelInfo == nil {
					m.ChannelInfo = []byte{}
				}
				i = to
				continue
			}
		case 9: // Client
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Client = string(s)
				i = to
				continue
			}
		case 10: // Data
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				m.Data = append(m.Data[:0], b[from:to]...)
				if m.Data == nil {
					m.Data = []byte{}
				}
				i = to
				continue
			}
		case 11: // RecoverSince
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.RecoverSince == nil {
					m.RecoverSince = new(StreamPosition)
				}
				if err := m.RecoverSince.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 12: // Session
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Session = string(s)
				i = to
				continue
			}
		case 13: // PushJoinLeave
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.PushJoinLeave = v != 0
				i = next
				continue
			}
		case 14: // Source
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Source = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 15: // LabelFilter
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.LabelFilter == nil {
					m.LabelFilter = new(FilterNode)
				}
				if err := m.LabelFilter.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 16: // AllUsers
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.AllUsers = v != 0
				i = next
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *StreamPosition) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.Offset != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Offset)
	}
	if m.Epoch != "" {
		n += 1 + len(m.Epoch) + cfprotobuf.SizeOfLen(len(m.Epoch))
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *StreamPosition) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *StreamPosition) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *StreamPosition) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.Epoch != "" {
		i -= len(m.Epoch)
		copy(b[i:], m.Epoch)
		i = cfprotobuf.PutLen(b, i, len(m.Epoch))
		i--
		b[i] = 0x12
	}
	if m.Offset != 0 {
		i = cfprotobuf.PutInt(b, i, m.Offset)
		i--
		b[i] = 0x8
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *StreamPosition) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *StreamPosition) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // Offset
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Offset = cfprotobuf.Int[uint64](v)
				i = next
				continue
			}
		case 2: // Epoch
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Epoch = string(s)
				i = to
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *FilterNode) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.Op != "" {
		n += 1 + len(m.Op) + cfprotobuf.SizeOfLen(len(m.Op))
	}
	if m.Key != "" {
		n += 1 + len(m.Key) + cfprotobuf.SizeOfLen(len(m.Key))
	}
	if m.Cmp != "" {
		n += 1 + len(m.Cmp) + cfprotobuf.SizeOfLen(len(m.Cmp))
	}
	if m.Val != "" {
		n += 1 + len(m.Val) + cfprotobuf.SizeOfLen(len(m.Val))
	}
	for _, e := range m.Vals {
		n += 1 + len(e) + cfprotobuf.SizeOfLen(len(e))
	}
	for _, e := range m.Nodes {
		n += 1 + cfprotobuf.SizeOfMessage(e.SizeCF())
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *FilterNode) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *FilterNode) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *FilterNode) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	for n := len(m.Nodes) - 1; n >= 0; n-- {
		{
			size, err := m.Nodes[n].MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x32
	}
	for n := len(m.Vals) - 1; n >= 0; n-- {
		i -= len(m.Vals[n])
		copy(b[i:], m.Vals[n])
		i = cfprotobuf.PutLen(b, i, len(m.Vals[n]))
		i--
		b[i] = 0x2a
	}
	if m.Val != "" {
		i -= len(m.Val)
		copy(b[i:], m.Val)
		i = cfprotobuf.PutLen(b, i, len(m.Val))
		i--
		b[i] = 0x22
	}
	if m.Cmp != "" {
		i -= len(m.Cmp)
		copy(b[i:], m.Cmp)
		i = cfprotobuf.PutLen(b, i, len(m.Cmp))
		i--
		b[i] = 0x1a
	}
	if m.Key != "" {
		i -= len(m.Key)
		copy(b[i:], m.Key)
		i = cfprotobuf.PutLen(b, i, len(m.Key))
		i--
		b[i] = 0x12
	}
	if m.Op != "" {
		i -= len(m.Op)
		copy(b[i:], m.Op)
		i = cfprotobuf.PutLen(b, i, len(m.Op))
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *FilterNode) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *FilterNode) unmarshalCF(b []byte, depth int) error {
	depth++
	if depth > cfprotobuf.MaxDepth {
		return cfprotobuf.ErrTooDeep
	}
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // Op
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Op = string(s)
				i = to
				continue
			}
		case 2: // Key
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Key = string(s)
				i = to
				continue
			}
		case 3: // Cmp
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Cmp = string(s)
				i = to
				continue
			}
		case 4: // Val
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Val = string(s)
				i = to
				continue
			}
		case 5: // Vals
			if tag&7 == 2 {
				var e string
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				e = string(s)
				i = to
				m.Vals = append(m.Vals, e)
				continue
			}
		case 6: // Nodes
			if tag&7 == 2 {
				e := new(FilterNode)
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if err := e.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				m.Nodes = append(m.Nodes, e)
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *Unsubscribe) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.Channel != "" {
		n += 1 + len(m.Channel) + cfprotobuf.SizeOfLen(len(m.Channel))
	}
	if m.User != "" {
		n += 1 + len(m.User) + cfprotobuf.SizeOfLen(len(m.User))
	}
	if m.Client != "" {
		n += 1 + len(m.Client) + cfprotobuf.SizeOfLen(len(m.Client))
	}
	if m.Session != "" {
		n += 1 + len(m.Session) + cfprotobuf.SizeOfLen(len(m.Session))
	}
	if m.Code != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Code)
	}
	if m.Reason != "" {
		n += 1 + len(m.Reason) + cfprotobuf.SizeOfLen(len(m.Reason))
	}
	if m.LabelFilter != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.LabelFilter.SizeCF())
	}
	if m.AllUsers {
		n += 1 + 1
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *Unsubscribe) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *Unsubscribe) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *Unsubscribe) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.AllUsers {
		i--
		b[i] = 1
		i--
		b[i] = 0x40
	}
	if m.LabelFilter != nil {
		{
			size, err := m.LabelFilter.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x3a
	}
	if m.Reason != "" {
		i -= len(m.Reason)
		copy(b[i:], m.Reason)
		i = cfprotobuf.PutLen(b, i, len(m.Reason))
		i--
		b[i] = 0x32
	}
	if m.Code != 0 {
		i = cfprotobuf.PutInt(b, i, m.Code)
		i--
		b[i] = 0x28
	}
	if m.Session != "" {
		i -= len(m.Session)
		copy(b[i:], m.Session)
		i = cfprotobuf.PutLen(b, i, len(m.Session))
		i--
		b[i] = 0x22
	}
	if m.Client != "" {
		i -= len(m.Client)
		copy(b[i:], m.Client)
		i = cfprotobuf.PutLen(b, i, len(m.Client))
		i--
		b[i] = 0x1a
	}
	if m.User != "" {
		i -= len(m.User)
		copy(b[i:], m.User)
		i = cfprotobuf.PutLen(b, i, len(m.User))
		i--
		b[i] = 0x12
	}
	if m.Channel != "" {
		i -= len(m.Channel)
		copy(b[i:], m.Channel)
		i = cfprotobuf.PutLen(b, i, len(m.Channel))
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Unsubscribe) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *Unsubscribe) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // Channel
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Channel = string(s)
				i = to
				continue
			}
		case 2: // User
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.User = string(s)
				i = to
				continue
			}
		case 3: // Client
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Client = string(s)
				i = to
				continue
			}
		case 4: // Session
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Session = string(s)
				i = to
				continue
			}
		case 5: // Code
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Code = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 6: // Reason
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Reason = string(s)
				i = to
				continue
			}
		case 7: // LabelFilter
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.LabelFilter == nil {
					m.LabelFilter = new(FilterNode)
				}
				if err := m.LabelFilter.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 8: // AllUsers
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.AllUsers = v != 0
				i = next
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *Disconnect) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.User != "" {
		n += 1 + len(m.User) + cfprotobuf.SizeOfLen(len(m.User))
	}
	for _, e := range m.Whitelist {
		n += 1 + len(e) + cfprotobuf.SizeOfLen(len(e))
	}
	if m.Code != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Code)
	}
	if m.Reason != "" {
		n += 1 + len(m.Reason) + cfprotobuf.SizeOfLen(len(m.Reason))
	}
	if m.Reconnect {
		n += 1 + 1
	}
	if m.Client != "" {
		n += 1 + len(m.Client) + cfprotobuf.SizeOfLen(len(m.Client))
	}
	if m.Session != "" {
		n += 1 + len(m.Session) + cfprotobuf.SizeOfLen(len(m.Session))
	}
	if m.LabelFilter != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.LabelFilter.SizeCF())
	}
	if m.AllUsers {
		n += 1 + 1
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *Disconnect) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *Disconnect) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *Disconnect) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.AllUsers {
		i--
		b[i] = 1
		i--
		b[i] = 0x48
	}
	if m.LabelFilter != nil {
		{
			size, err := m.LabelFilter.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x42
	}
	if m.Session != "" {
		i -= len(m.Session)
		copy(b[i:], m.Session)
		i = cfprotobuf.PutLen(b, i, len(m.Session))
		i--
		b[i] = 0x3a
	}
	if m.Client != "" {
		i -= len(m.Client)
		copy(b[i:], m.Client)
		i = cfprotobuf.PutLen(b, i, len(m.Client))
		i--
		b[i] = 0x32
	}
	if m.Reconnect {
		i--
		b[i] = 1
		i--
		b[i] = 0x28
	}
	if m.Reason != "" {
		i -= len(m.Reason)
		copy(b[i:], m.Reason)
		i = cfprotobuf.PutLen(b, i, len(m.Reason))
		i--
		b[i] = 0x22
	}
	if m.Code != 0 {
		i = cfprotobuf.PutInt(b, i, m.Code)
		i--
		b[i] = 0x18
	}
	for n := len(m.Whitelist) - 1; n >= 0; n-- {
		i -= len(m.Whitelist[n])
		copy(b[i:], m.Whitelist[n])
		i = cfprotobuf.PutLen(b, i, len(m.Whitelist[n]))
		i--
		b[i] = 0x12
	}
	if m.User != "" {
		i -= len(m.User)
		copy(b[i:], m.User)
		i = cfprotobuf.PutLen(b, i, len(m.User))
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Disconnect) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *Disconnect) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // User
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.User = string(s)
				i = to
				continue
			}
		case 2: // Whitelist
			if tag&7 == 2 {
				var e string
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				e = string(s)
				i = to
				m.Whitelist = append(m.Whitelist, e)
				continue
			}
		case 3: // Code
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Code = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 4: // Reason
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Reason = string(s)
				i = to
				continue
			}
		case 5: // Reconnect
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Reconnect = v != 0
				i = next
				continue
			}
		case 6: // Client
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Client = string(s)
				i = to
				continue
			}
		case 7: // Session
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Session = string(s)
				i = to
				continue
			}
		case 8: // LabelFilter
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.LabelFilter == nil {
					m.LabelFilter = new(FilterNode)
				}
				if err := m.LabelFilter.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 9: // AllUsers
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.AllUsers = v != 0
				i = next
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *SurveyRequest) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.Id != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Id)
	}
	if m.Op != "" {
		n += 1 + len(m.Op) + cfprotobuf.SizeOfLen(len(m.Op))
	}
	if len(m.Data) > 0 {
		n += 1 + len(m.Data) + cfprotobuf.SizeOfLen(len(m.Data))
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *SurveyRequest) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *SurveyRequest) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *SurveyRequest) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(b[i:], m.Data)
		i = cfprotobuf.PutLen(b, i, len(m.Data))
		i--
		b[i] = 0x1a
	}
	if m.Op != "" {
		i -= len(m.Op)
		copy(b[i:], m.Op)
		i = cfprotobuf.PutLen(b, i, len(m.Op))
		i--
		b[i] = 0x12
	}
	if m.Id != 0 {
		i = cfprotobuf.PutInt(b, i, m.Id)
		i--
		b[i] = 0x8
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *SurveyRequest) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *SurveyRequest) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // Id
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Id = cfprotobuf.Int[uint64](v)
				i = next
				continue
			}
		case 2: // Op
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Op = string(s)
				i = to
				continue
			}
		case 3: // Data
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				m.Data = append(m.Data[:0], b[from:to]...)
				if m.Data == nil {
					m.Data = []byte{}
				}
				i = to
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *SurveyResponse) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.Id != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Id)
	}
	if m.Code != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Code)
	}
	if len(m.Data) > 0 {
		n += 1 + len(m.Data) + cfprotobuf.SizeOfLen(len(m.Data))
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *SurveyResponse) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *SurveyResponse) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *SurveyResponse) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(b[i:], m.Data)
		i = cfprotobuf.PutLen(b, i, len(m.Data))
		i--
		b[i] = 0x1a
	}
	if m.Code != 0 {
		i = cfprotobuf.PutInt(b, i, m.Code)
		i--
		b[i] = 0x10
	}
	if m.Id != 0 {
		i = cfprotobuf.PutInt(b, i, m.Id)
		i--
		b[i] = 0x8
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *SurveyResponse) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *SurveyResponse) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // Id
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Id = cfprotobuf.Int[uint64](v)
				i = next
				continue
			}
		case 2: // Code
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Code = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 3: // Data
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				m.Data = append(m.Data[:0], b[from:to]...)
				if m.Data == nil {
					m.Data = []byte{}
				}
				i = to
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *Notification) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.Op != "" {
		n += 1 + len(m.Op) + cfprotobuf.SizeOfLen(len(m.Op))
	}
	if len(m.Data) > 0 {
		n += 1 + len(m.Data) + cfprotobuf.SizeOfLen(len(m.Data))
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *Notification) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *Notification) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *Notification) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(b[i:], m.Data)
		i = cfprotobuf.PutLen(b, i, len(m.Data))
		i--
		b[i] = 0x12
	}
	if m.Op != "" {
		i -= len(m.Op)
		copy(b[i:], m.Op)
		i = cfprotobuf.PutLen(b, i, len(m.Op))
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Notification) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *Notification) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // Op
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Op = string(s)
				i = to
				continue
			}
		case 2: // Data
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				m.Data = append(m.Data[:0], b[from:to]...)
				if m.Data == nil {
					m.Data = []byte{}
				}
				i = to
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeCF returns the size of the Protobuf encoding of m.
func (m *Refresh) SizeCF() (n int) {
	if m == nil {
		return 0
	}
	if m.User != "" {
		n += 1 + len(m.User) + cfprotobuf.SizeOfLen(len(m.User))
	}
	if m.Client != "" {
		n += 1 + len(m.Client) + cfprotobuf.SizeOfLen(len(m.Client))
	}
	if m.Expired {
		n += 1 + 1
	}
	if m.ExpireAt != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.ExpireAt)
	}
	if len(m.Info) > 0 {
		n += 1 + len(m.Info) + cfprotobuf.SizeOfLen(len(m.Info))
	}
	if m.Session != "" {
		n += 1 + len(m.Session) + cfprotobuf.SizeOfLen(len(m.Session))
	}
	if m.LabelFilter != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.LabelFilter.SizeCF())
	}
	if m.AllUsers {
		n += 1 + 1
	}
	n += len(m.unknownFields)
	return n
}

// MarshalCF returns the Protobuf encoding of m.
func (m *Refresh) MarshalCF() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeCF())
	n, err := m.MarshalToSizedBufferCF(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToCF writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeCF bytes, and returns the number of bytes written.
func (m *Refresh) MarshalToCF(b []byte) (int, error) {
	return m.MarshalToSizedBufferCF(b[:m.SizeCF()])
}

// MarshalToSizedBufferCF writes the Protobuf encoding of m to the end of b, which
// must have room for SizeCF bytes, and returns the number of bytes written.
func (m *Refresh) MarshalToSizedBufferCF(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.AllUsers {
		i--
		b[i] = 1
		i--
		b[i] = 0x40
	}
	if m.LabelFilter != nil {
		{
			size, err := m.LabelFilter.MarshalToSizedBufferCF(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x3a
	}
	if m.Session != "" {
		i -= len(m.Session)
		copy(b[i:], m.Session)
		i = cfprotobuf.PutLen(b, i, len(m.Session))
		i--
		b[i] = 0x32
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(b[i:], m.Info)
		i = cfprotobuf.PutLen(b, i, len(m.Info))
		i--
		b[i] = 0x2a
	}
	if m.ExpireAt != 0 {
		i = cfprotobuf.PutInt(b, i, m.ExpireAt)
		i--
		b[i] = 0x20
	}
	if m.Expired {
		i--
		b[i] = 1
		i--
		b[i] = 0x18
	}
	if m.Client != "" {
		i -= len(m.Client)
		copy(b[i:], m.Client)
		i = cfprotobuf.PutLen(b, i, len(m.Client))
		i--
		b[i] = 0x12
	}
	if m.User != "" {
		i -= len(m.User)
		copy(b[i:], m.User)
		i = cfprotobuf.PutLen(b, i, len(m.User))
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalCF decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Refresh) UnmarshalCF(b []byte) error {
	return m.unmarshalCF(b, 0)
}

func (m *Refresh) unmarshalCF(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // User
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.User = string(s)
				i = to
				continue
			}
		case 2: // Client
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Client = string(s)
				i = to
				continue
			}
		case 3: // Expired
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Expired = v != 0
				i = next
				continue
			}
		case 4: // ExpireAt
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.ExpireAt = cfprotobuf.Int[int64](v)
				i = next
				continue
			}
		case 5: // Info
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				m.Info = append(m.Info[:0], b[from:to]...)
				if m.Info == nil {
					m.Info = []byte{}
				}
				i = to
				continue
			}
		case 6: // Session
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Session = string(s)
				i = to
				continue
			}
		case 7: // LabelFilter
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.LabelFilter == nil {
					m.LabelFilter = new(FilterNode)
				}
				if err := m.LabelFilter.unmarshalCF(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 8: // AllUsers
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.AllUsers = v != 0
				i = next
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}
