// Package protocent defines helper methods to build custom Centrifuge engines.
package protocent

import (
	"github.com/centrifugal/centrifuge/internal/proto"
)

// PushType ...
type PushType proto.PushType

// Define several aliases to internal protocol types generated by gogoprotobuf.
// This allows to build custom engine implementation without having access to
// other internal protocol structures.
type (
	Push = proto.Push
)

// Push types.
var (
	PushTypeJoin        = proto.PushTypeJoin
	PushTypeLeave       = proto.PushTypeLeave
	PushTypePublication = proto.PushTypePublication
)
