// Package protocent defines helper methods to build custom Centrifuge engines.
package protocent

import (
	"github.com/centrifugal/centrifuge/internal/proto"
)

// Define several aliases to internal protocol types generated by gogoprotobuf.
// This allows to build custom engine implementation without having access to
// other internal client protocol structures.
type (
	// Push wraps Publication, Join or Leave.
	Push = proto.Push
)

// Push types.
var (
	PushTypePublication = proto.PushTypePublication
	PushTypeJoin        = proto.PushTypeJoin
	PushTypeLeave       = proto.PushTypeLeave
)
